### ISSUE TITLE
input Binding on multiple cameras

### ISSUE THREAD

**Issue by ChristopherO1** [bartbutenaers/node-red-contrib-ui-svg#33]
I'm having a problem with my input Binding.
I have a simple floor plan with three cameras added

I have injector nodes that change the fill attribute of the cameras.
The problem I'm seeing is...
Whichever camera I try to change the colour of, it always adjusts the one that is top of the list in the input Binding Tab.

I've attached my flow, as a zip file.

There are animations in there as well, these behave as I expected them too

If this is a case of user error, please close

[flow.zip](https://github.com/bartbutenaers/node-red-contrib-ui-svg/files/3630400/flow.zip)

**Comment by ChristopherO1** [comment]
I also keep seeing this, maybe relevant

![inputBinding](https://user-images.githubusercontent.com/41161090/65236690-08131880-dad1-11e9-9b76-92cba656b958.PNG)

**Comment by bartbutenaers** [comment]
Hi  @ChristopherO1,

Thanks for the feedback!

## Uncomplete Input Binding tabsheet 
This was indeed a bug, so I have fixed this in the DEV branch.

## First binding camera is always updated
As I explained already in the forum, the absence of updated documentation is one of the main reasons that I haven't published this beta on the forum yet.  And I want avoid having to explain it to everybody in advance, otherwise I have no time left to finish my beta version ...

Anyway, this explanation is hopefully a bit clear:
+ **Without bindings**: when you want to trigger something solely based on the content of the input message, the ```msg.payload.command``` or the ```msg.payload.topic``` should have one of the following values:
   + ***update_text***: To update the text of an SVG ```<text>``` element to the value specified in ```msg.payload.textContent```.
   + ***update_attribute***: to update the value of an *existing* SVG element attribute.  The attribute name needs to be specified in ```msg.payload.attributeName``` and the value in ```msg.payload.attributeValue```
   + ***set_attribute***: identical to update_attribute, but now the attribute will be created if it doesn't exist yet in the SVG element.
   + ***trigger_animation***: via ```msg.payload.action``` you need to specify a "start" or "stop" action.

    In all those cases you need to specify a single element id (without prefix "#") in ```msg.payload.elementId``` or a selection of elements in ```payload.selector```.

+ **With bindings**: when you want to trigger something without having to specify everything in the input message (to keep your flow simple), you need to add the same information now in the "Binding" tabsheet.  Now the ```msg.payload.topic``` should be ***databind*** and the msg only needs to contain zero or more fields corresponding to the values in the "Bind source" column.  For example in Steve's screenshot that I shared with you (on the [forum](https://discourse.nodered.org/t/control-via-messages-in-ui-svg/15654/6?u=bartbutenaers)):

   ![image](https://user-images.githubusercontent.com/14224149/65280442-a5516980-db30-11e9-9b57-a859c0b57cdb.png)

   So if you send a message containing ```payload.message``` or ```payload.xpos``` or both, then the corresponding values will be applied to the SVG elements that match with the "Selector" column...

So you use 3 data bindings with source "payload.attributeValue", which isn't really correct ...

I will add this information to the readme page as soon as I have time...

**Comment by ChristopherO1** [comment]
@bartbutenaers 
I've gone with the 'without bindings' option for now. Works as expected, perfect.
Thanks for the info, quick fix, and update.
I'll keep playing with the'with bindings' option

Thank You

**Comment by bartbutenaers** [comment]
@ChristopherO1,
Thanks very much for testing and for your constructive feedback!!  If there is anything not clear to my explanation above, please let me know!  I will try to update the readme page this weekend, so all tips are welcome!
