### ISSUE TITLE
Unresponsive SVG files

### ISSUE THREAD

**Issue by byunchov** [bartbutenaers/node-red-contrib-ui-svg#70]
Hi!
I have recentrly started wokring with your project and I quite like how easy it is to use. But i have faced some problems regarding the work with fairly vector crowded SVG files.
Currently I'm tinkering around trying to find what suits my needs, however I have stumbled upon an annoying bug regarding the interaction with the SVG file. When there is small number of vectors everyting works as expected. But when I add more vectors things start to act out strangely. The event handlers are not responding and I'm unable to change any of the vectors' proprties.
I've tought that maybe I'm doing something stupid and wrong, but when I have opened the console it was full of various errors. So i decided to open up an issue on GitHub and maybe help someone else with the same problem.
That's my Node Red test flow:
```
[{"id":"b1ed5962.a8bce8","type":"debug","z":"15a060b.ba89d9f","name":"Floorplan output","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","statusVal":"","statusType":"auto","x":640,"y":1820,"wires":[]},{"id":"4da1b9d.8237948","type":"ui_svg_graphics","z":"15a060b.ba89d9f","group":"7bb4a379.1539bc","order":1,"width":"0","height":"0","svgString":"<svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"950px\" height=\"415px\" viewBox=\"-0.025699207559227943 0 950.0513916015625 415\" preserveAspectRatio=\"xMinYMin meet\">\n  <rect id=\"svgEditorBackground\" x=\"0\" y=\"0\" width=\"1550\" height=\"710\" style=\"fill: none; stroke: none;\" />\n  <defs id=\"svgEditorDefs\">\n    <linearGradient gradientUnits=\"objectBoundingBox\" id=\"lgrd2-peachpuff-sienna-v\" spreadMethod=\"pad\" x1=\"0%\" x2=\"0%\" y1=\"0%\" y2=\"100%\">\n      <stop offset=\"0%\" style=\"stop-color:peachpuff;  stop-opacity:0.84;\" />\n      <stop offset=\"100%\" style=\"stop-color:sienna;  stop-opacity:1\" />\n    </linearGradient>\n    <radialGradient cx=\"50%\" cy=\"50%\" fx=\"50%\" fy=\"50%\" id=\"led-green\" r=\"50%\" gradientUnits=\"objectBoundingBox\" spreadMethod=\"pad\" gradientTransform=\"\">\n      <stop offset=\"0\" style=\"stop-opacity: 0.809; stop-color: rgb(50, 205, 50);\" />\n      <stop offset=\"1\" style=\"stop-color: rgb(0, 128, 0); stop-opacity: 0.884;\" />\n    </radialGradient>\n    <radialGradient cx=\"50%\" cy=\"50%\" fx=\"50%\" fy=\"50%\" id=\"led-red\" r=\"50%\" gradientUnits=\"objectBoundingBox\" spreadMethod=\"pad\" gradientTransform=\"\">\n      <stop offset=\"0\" style=\"stop-opacity: 0.809; stop-color: rgb(255, 99, 99);\" />\n      <stop offset=\"1\" style=\"stop-color: rgb(255, 0, 0); stop-opacity: 0.884;\" />\n    </radialGradient>\n    <linearGradient gradientUnits=\"objectBoundingBox\" id=\"lgrd2-black-white\" spreadMethod=\"pad\" x1=\"0%\" x2=\"100%\" y1=\"0%\" y2=\"100%\">\n      <stop offset=\"0%\" stop-color=\"black\" />\n      <stop offset=\"100%\" stop-color=\"white\" />\n    </linearGradient>\n    <polygon id=\"svgEditorIconDefs\" style=\"fill:rosybrown;\" />\n    <symbol xmlns=\"http://www.w3.org/2000/svg\" id=\"f769\" preserveAspectRatio=\"xMidYMid meet\" viewBox=\"0 0 512 512\">\n      <path d=\"M416 0c-52.9 0-96 43.1-96 96s43.1 96 96 96 96-43.1 96-96-43.1-96-96-96zm0 128c-17.7 0-32-14.3-32-32s14.3-32 32-32 32 14.3 32 32-14.3 32-32 32zm-160-16C256 50.1 205.9 0 144 0S32 50.1 32 112v166.5C12.3 303.2 0 334 0 368c0 79.5 64.5 144 144 144s144-64.5 144-144c0-34-12.3-64.9-32-89.5V112zM144 448c-44.1 0-80-35.9-80-80 0-25.5 12.2-48.9 32-63.8V112c0-26.5 21.5-48 48-48s48 21.5 48 48v192.2c19.8 14.8 32 38.3 32 63.8 0 44.1-35.9 80-80 80zm16-125.1V112c0-8.8-7.2-16-16-16s-16 7.2-16 16v210.9c-18.6 6.6-32 24.2-32 45.1 0 26.5 21.5 48 48 48s48-21.5 48-48c0-20.9-13.4-38.5-32-45.1z\" />\n    </symbol>\n    <linearGradient gradientUnits=\"objectBoundingBox\" id=\"termomrter\" spreadMethod=\"pad\" x1=\"8.4%\" x2=\"97%\" y1=\"100%\" y2=\"31%\">\n      <stop offset=\"0\" stop-color=\"black\" style=\"stop-opacity: 0.916;\" />\n      <stop offset=\"100%\" stop-color=\"#404040\" style=\"stop-opacity: 1;\" />\n    </linearGradient>\n  </defs>\n  <circle id=\"e1_circle\" cx=\"126.871\" cy=\"59.452\" style=\"fill:url(#led-green);stroke:black;stroke-width:1px;\" r=\"23.403\" />\n  <ellipse id=\"e2_ellipse\" cx=\"448.5292053222656\" cy=\"110.58894348144533\" style=\"fill:url(#lgrd2-peachpuff-sienna-v);stroke:black;stroke-width:1px;\" rx=\"129.32258064516128\" ry=\"79.67741935483866\" />\n  <rect x=\"242.5\" y=\"245\" style=\"fill: url(#termomrter); stroke-width: 1px;stroke:silver;\" id=\"e3_rectangle\" width=\"160\" height=\"105\" rx=\"10\" ry=\"10\" />\n  <text style=\"fill:black;font-family:Arial;font-size:20px;\" x=\"301.043\" y=\"277.276\" id=\"e1_texte\" /><text style=\"fill:black;font-family:Arial;font-size:20px;\" x=\"641.696\" y=\"258.385\" id=\"e2_texte\" />\n  <rect x=\"285\" y=\"252.5\" style=\"fill:black;stroke:none;stroke-width:1px;\" id=\"e2_rectangle\" width=\"110\" height=\"65\" rx=\"5\" />\n  <text style=\"fill:firebrick; font-family: &quot;Arial Black&quot;; font-size: 50pt; font-weight: bolder; text-anchor: end;\" x=\"390.0000915527344\" y=\"305.99993896484375\" id=\"temp_in\">100</text>\n  <circle id=\"e2_circle\" cx=\"270\" cy=\"270\" style=\"fill:url(#led-green);stroke:none;stroke-width:1px;\" r=\"25\" transform=\"matrix(0.375995 0 0 0.375995 158.477 160.211)\" />\n  <text style=\"fill:white;font-family:Arial Black;font-size:20pt;font-weight:bolder;text-anchor:middle;\" x=\"263\" y=\"314\" id=\"e4_texte\">°C</text>\n  <rect x=\"415.00015146756834\" y=\"245\" style=\"fill: url(#termomrter); stroke-width: 1px;stroke:silver;\" id=\"e4_rectangle\" width=\"165\" height=\"105\" rx=\"10\" ry=\"10\" />\n  <rect x=\"452.50015146756834\" y=\"252.5\" style=\"fill:black;stroke:black;stroke-width:1px;\" id=\"e1_rectangle\" width=\"120\" height=\"65\" rx=\"5\" />\n  <text style=\"fill:firebrick; font-family: &quot;Arial Black&quot;; font-size:48pt; font-weight: bolder; text-anchor: end;\" x=\"569.2001342773438\" y=\"307\" id=\"e1_in\">99.9</text>\n  <circle id=\"e3_circle\" cx=\"724.9999466874528\" cy=\"270\" style=\"fill:url(#led-green);stroke:none;stroke-width:1px;\" r=\"25\" transform=\"matrix(0.375995 0 0 0.375995 158.477 160.211)\" />\n  <text style=\"fill:white;font-family:Arial Black;font-size:20pt;font-weight:bolder;text-anchor:middle;\" x=\"434.0001525878906\" y=\"314\" id=\"e3_texte\">°C</text>\n  <text style=\"fill:white;font-family:Arial Black;font-size:20px;font-weight:bold;text-anchor:middle;\" x=\"322.0000305175781\" y=\"340.00006103515625\" id=\"e5_texte\">ВХОД</text>\n  <text style=\"fill:white;font-family:Arial Black;font-size:20px;font-weight:bold;text-anchor:middle;\" x=\"750\" y=\"340\" id=\"e6_texte\" dx=\"0\" dy=\"0\">ВХОД</text>\n  <text style=\"fill:white;font-family:Arial Black;font-size:20px;font-weight:bold;text-anchor:middle;\" x=\"495.5\" y=\"340\" id=\"e7_texte\">ИЗХОД</text>\n</svg>","clickableShapes":[{"targetId":"#e1_circle","action":"click","payload":"#e1_circle","payloadType":"str","topic":"#e1_circle"}],"smilAnimations":[],"bindings":[{"selector":"#temp_in","bindSource":"payload.tin","bindType":"text","attribute":""}],"showCoordinates":false,"autoFormatAfterEdit":true,"showBrowserErrors":false,"outputField":"","editorUrl":"http://drawsvg.org/drawsvg.html","directory":"","panning":"disabled","zooming":"disabled","panOnlyWhenZoomed":false,"doubleClickZoomEnabled":false,"mouseWheelZoomEnabled":false,"name":"","x":440,"y":1820,"wires":[["b1ed5962.a8bce8"]]},{"id":"3e8e0aeb.4dc8d6","type":"inject","z":"15a060b.ba89d9f","name":"manual injector","props":[{"p":"topic","vt":"str"},{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"databind","payload":"{\"tin\":105}","payloadType":"json","x":240,"y":1800,"wires":[["4da1b9d.8237948"]]},{"id":"1653de5d.358ab2","type":"inject","z":"15a060b.ba89d9f","name":"selector","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"{\"command\":\"update_text\",\"selector\":\"#temp_in\",\"textContent\":105}","payloadType":"json","x":210,"y":1840,"wires":[["4da1b9d.8237948"]]},{"id":"7bb4a379.1539bc","type":"ui_group","z":"","name":"Floorplan test","tab":"7b74af43.9058a","order":1,"disp":true,"width":"18","collapse":false},{"id":"7b74af43.9058a","type":"ui_tab","z":"","name":"SVG","icon":"dashboard","disabled":false,"hidden":false}]
```
I have also appended the console log file so you colud get a clearer picture of what may be going on.
[console.log](https://github.com/bartbutenaers/node-red-contrib-ui-svg/files/5269499/console.log)
I'm sorry if I have opened a new issue for the same problem.
Every guidance is appreciated.
Thanks in advance.

**Comment by bartbutenaers** [comment]
Hi Bozhidar (@byunchov),
Sorry for the delay.  I must be getting nuts: I investigated 6 days ago your issue, fixed it on Github (as you can see in the history of the code), and added a large explanation of the solution here.  But I must have forgotten somehow to post my comment ...

Summarized: You have a few times `&quot;` in your svg, which causes AngularJs to raise a parsing exception (which you can see when you have a look at your browser console log, where you are displaying your dashboard).  I assume you don't use DrawSvg (because the recent version shouldn't generate those  `&quot;` anymore), but instead you have used some third party SVG editor?  

It is now fixed on Github (***not*** on NPM yet!), so you should be able to solve it in two different ways:
+ Remove manually those  `&quot;` a couple of times in your SVG string.
+ Install the latest version directly from Github, from within your .node-red folder:
   ```
   npm install bartbutenaers/node-red-contrib-ui-svg
   ```

Would be nice if you could test my fix (second solution), and let me know whether it works.  Then I can publish the fix on NPM. 

Thanks and sorry for the (unwanted) delay!
Bart

**Comment by byunchov** [comment]
Thank you Bart (@bartbutenaers)!
I have installed the latest version directly from Github and everything seem to work as expected. I have noticed the ```&quot;``` in the document generated from DrawSVG, but Ididn't suspect that it was the main culprit. Thank you for the reply. I have managed to solve the problem with the node-red-contrib-dashboard template node and  little bit of JS magic. I will stick to this solution as it gives me some flexibility on howI handle click events. I will try to implement my idea with your repo as well and if you'd like I would give you a feed back of how it all turned out to be
Don't be so worried about the delay. I know how hard it is to keep up with a lot of work over your head.

**Comment by bartbutenaers** [comment]
Thanks for the fast response!

>  it gives me some flexibility on howI handle click events.

If there are any improvements I can make to allow the same behaviour, please let me know!

**Comment by byunchov** [comment]
I feel how my issue report is slowly phasing into a feature request. 
Maybe I should have given more information about what I am trying to achieve.
Me and my brother are making a pellet line consisting of furnace, drying drum, suction cyclone, shredder and a handfull of other noisy machinery. My goal is to make the process almost fully autonomous with dummy-friendly GUI, which is not crappy looking and is feature dence. I stumbled upon your nice project and honestly I really liked what functionalities it offered. Unfortunately I was unable to play around with all of this, because of this small bug.
I will use my DXF files from my layout plans to turn them into SVG in scale. What I want is when particular graphic is clicked a specific SVG filter to be applied so that it mimics the behaviour of a toggle button. Then, depending on the current state of the button after a reset button is pressed the selected machine to be turned on/off and the state of the selector graphics to be restet to normal (the filter to be cleared). Rigth now I do it in JS and I know there migth be a workaround with a fuction node and maybe some other nodes but the flow gets crowded  considering that I will have 20+ "selectors". If you are interesetd I could share my dummy code and maybe we could figure something out?

**Comment by bartbutenaers** [comment]
> I feel how my issue report is slowly phasing into a feature request.

Well ideas - that are generally usable for more users - are always welcome!  But due to my lack of free time, make sure to describe shortly why/what/how a new feature would look like.

> I will use my DXF files from my layout plans to turn them into SVG in scale

Ah ok, I assume the `&quot;` will get be inserted somewhere in that process ...

> What I want is when particular graphic is clicked a specific SVG filter to be applied so that it mimics the behaviour of a toggle button.

I assume you mean this part of your template node code:
```
    ciclon.on('click', function(){
        state.ciclon ^= 1;
        if(ciclon.attr("filter") === ""){
            ciclon.attr("filter", "url(#innershadow)");
        }
        else{
            ciclon.attr("filter", "");
        }
    });
```

Indeed the SVG node doesn't work currently with client side event handling:
1.  You can specify an event for an svg shape.
2. As soon as the specified shape is being clicked, the info will be send to the server where an output message will be send.
3. That output message can be used as input message again, e.g. to activate the filter (via e.g. a function node).
4. The information from that input message will be send to the client again.
5. The filter will be applied to the specified shape on the client.

But of course then you will get an entire roundtrip (client -> server -> client), which will introduce delays which might not be acceptable in your case.

Currently it is not possible to specify javascript code in the config screen, which needs to be executed as event handler on the client side.  And it is currently also not possible to trigger an `addEventListener` via an input message, where you can specify the javascript inside the input message.  

It is not clear to me if that is your feature request??  Or something else??

**Comment by byunchov** [comment]
I was going to suggest you to add the ability to insert JS code in the config screen for the client side. My second suggestion is targeted more towards this "toggle button" effect wich I think if you are trying to implement without some JS blueprint makes it hard to work with (not that it's impossible to do so). I don't know what could be handy for all, but in my use case the ability to have some kind of interaction via JS would be appreciated.
Not quite sure it wolud be of much help for you, though. Just sharing my opinion. Unfotunately, it's hard for me to describe what's inside my head.

**Comment by bartbutenaers** [comment]
Yes I can understand that this might be interesting, but not sure how to proceed with it.  
+ Adding a Js event handler via the input message should be 'rather' simple, by adding a new [event](https://github.com/bartbutenaers/node-red-contrib-ui-svg#add-events-via-msg) command.  For example:
   ```
   "payload": {
      "command"  : "add_client_event",
      "event"    : "click",
      "selector" : "#circle_2", 
      "js"       : "some javascript event handling code"
   }]
   ```
+ But not sure how to implement this in the config screen, since there is no [TypedInput ](https://nodered.org/docs/api/ui/typedInput/#options-types) in Node-RED that supports Javascript input.  And I have no time at the moment to add an ACE editor to the config screen.

My time is up for today ...

**Comment by bartbutenaers** [comment]
Hi Bozhidar,

Of course you can simply add you event handler inside your SVG source:
```
<svg viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg">
  <circle cx="30" cy="30" r="20" fill="blue" cursor="pointer" onclick="alert('Click event handled on the client ...')" />
</svg>
```
However then you need to add it again, every time you have edited your SVG (using an external SVG editor).

I have created last night a _"client-side-event-handle"_ branch, that allows [setting a client-side event handler](https://github.com/bartbutenaers/node-red-contrib-ui-svg/blob/client-side-event-handler/README.md#add-client-side-events-via-msg) via input messages (similar to the server-side event handlers).  You can install that branch like this (from within your .node-red folder) if you want:
```
npm install bartbutenaers/node-red-contrib-ui-svg#client-side-event-handler
```
However I have no idea yet how to integrate such functionality into the "Events" tabsheet.  When I create a custom typedinput (for Javascript), it looks very confusing (since the column headers don't match the content of the columns anymore):

![image](https://user-images.githubusercontent.com/14224149/94856078-bf09da00-042f-11eb-871b-1f4a6b894703.png)

Moreover the Javascript field is way too small, and there is no syntax highlighting...

**Comment by bartbutenaers** [comment]
@byunchov ,
I'm not sure whether you still use this SVG node, or the template node.
I found a way to implement the Javascript event handlers.
The beta version will now be discussed on the Node-RED [forum](https://discourse.nodered.org/t/announce-node-red-contrib-ui-svg-2-1-0-beta/35093).
If you want to test it, please let me know whether it works correctly.

**Comment by byunchov** [comment]
Thank you for updating me, @bartbutenaers !
I'm sorry for the delay but I got side tracked with several different projects and tottally forgot to write you back. I'll give the beta version a try ASAP.
Have a nice day!

**Comment by bartbutenaers** [comment]
Version 2.1.0 is now published on NPM.
