### ISSUE TITLE
Documentation badly formatted

### ISSUE THREAD

**Issue by OrlandodaSilva** [bartbutenaers/node-red-contrib-ui-svg#74]
Hi, I have been using your documentation on 
https://flows.nodered.org/node/node-red-contrib-ui-svg/in/590bc13ff3a5f005c7d2189bbb563976
If you scroll to the very bottom you will notice that the document appears to be corrupt. 
Is it possible to have it corrected or is it outside your scope.

**Comment by bartbutenaers** [comment]
Hi,
This has already been reported on the Node-RED [forum](https://discourse.nodered.org/t/problem-with-example-at-node-info-node-red-contrib-ui-svg-2-0-3/34428/4?u=bartbutenaers).  But got no feedback on that yet.  I assume it is a bug of the site...
Bart

**Comment by tttdevelop** [comment]
Can you put the code for "Set text content via msg" in the wiki here so we can still copy and see how you do things while you wait for feedback from the Node Red forum. I am interesting how you did this. Thanks !

**Comment by bartbutenaers** [comment]
@OrlandodaSilva,
Last week Nick reported that the lenth of the readme page should be limited, because the NPM API (which he calls to copy the readme to flows.nodered.org) truncates the pages at some length.  So only thing I can do is to split my readme page into multiple pages...

@tttdevelop,
Until I have split the readme page for NPM, you can always see the full readme page here in this Github repository.  Or did I misinterpret your question perhaps?

**Comment by tttdevelop** [comment]
@bartbutenaers - Nope. Your answer is perfect. Didn't think about looking at the README.MD. I was looking at your wiki.

**Comment by bartbutenaers** [comment]
I have split the [readme](https://github.com/bartbutenaers/node-red-contrib-ui-svg/blob/master/README.md) page on Github into multiple files.  Hopefully it will become now more readable on npm and flows.nodered.org.
This change will be published on npm very soon, as part of the ***2.2.0*** release.

**Comment by bartbutenaers** [comment]
Version _**2.2.0**_ has been published on NPM, which contains a smaller readme page (with links to other pages).
