### ISSUE TITLE
Messages not forwarded with 2.1.0

### ISSUE THREAD

**Issue by breezah123** [bartbutenaers/node-red-contrib-ui-svg#78]
Hi,
 The new 2.1.0 does not seem to forward the messages anymore, maybe in favour of the new JS-Tab, so the flow-data only contains coordinates of the click. As I built anything with JS-functions afterwards, I can not put this into the JS-Tab easily. 2.0.0 does work, when I downgrade. Beside this: excellent work, very useful, thanks very much for that.

**Comment by bartbutenaers** [comment]
Hi @breezah123 ,
Thanks for reporting.  Somebody else posted the same [issue ](https://github.com/bartbutenaers/node-red-contrib-ui-svg/issues/77)today, so I'm going to close this one.
You can see there that I have published a fix a couple of minutes ago. 
If you still have problems, please reply in the other discussion.  Because that is easier for me to do the follow-up...
Bart
