### ISSUE TITLE
Request: a version that works with m dashboard

### ISSUE THREAD

**Issue by LionyxML** [bartbutenaers/node-red-contrib-ui-svg#81]
I recently had to migrate an application to mdashboard, so it allows a multiuser environment.

Is there a quick and dirty way (or maybe a cool fork) to make this work with mui and not only ui?

Thanks!

**Comment by bartbutenaers** [comment]
Hi Rahul,
Some time ago the guys from Hitachi have added some changes to the standard dashboard, to allow contributors like me to develop UI nodes.
If the developer of the mdashboard has merged those changes into his dashboard fork, then I assume it would be possible somehow.  Otherwise you have bad luck.
Personally I don't like such forks, because it will take a lot of effort to keep it sync with the new features/bugfixes in the original fork.
So I'm going to close this, because you have to ask it this question to him.
Good luck!
Bart
