### ISSUE TITLE
Manual / automatic sorting of the entered Event-elements

### ISSUE THREAD

**Issue by JoeWiseman** [bartbutenaers/node-red-contrib-ui-svg#90]
Hi developer,

when I was in the process of creating a somewhat more complex GUI, I noticed that the **events** entered also grow "organically". However, some of them should rather be placed next to each other for the sake of clarity.

Is it possible that the **event**- elements 
- be moved manually (as is the case with the queries in the _switch node_)?
- Is there a _button_ that sorts all events alphabetically?

That would be a real help for larger projects.

Best regards
Joe

**Comment by bartbutenaers** [comment]
Hi Joe,
I could easily add the icon to allow you to reorder the lines manually.  
Problem is that I have not much space.
Will try something this week.  Please remind me if I have forgotten about it!
Bart

**Comment by bartbutenaers** [comment]
Hey Joe,

Version ***2.2.1*** has been published on NPM, which allows the events to be reordered manually (as you can see [here](https://discourse.nodered.org/t/announce-node-red-contrib-ui-svg/17063/88?u=bartbutenaers)).

For the ***sort button*** it is a bit more complicated, because Node-RED currently doesn't allow custom buttons to be added to an editableList (= widget where e.g. the events are being displayed).  So I have created two pull requests (see [this](https://discourse.nodered.org/t/custom-button-for-editablelist/41342/7?u=bartbutenaers) discussion) to add this feature to the Node-RED core...

So I suggest that we keep this issue open, and as soon as Nick has merged my pull request (hopefully in Node-RED 1.3 which will be released as a beta version very soon) then I can add that button without workarounds.

**Comment by JoeWiseman** [comment]
Hi Bart,

don't worry about automatically reordering the Event-list the work you've done with manually reordering is great!!!!
If there will be any further realeases which supports the auto-reorder-feature than I will be happy too.... So if you kepp that in mind then I will close this "issue"

I've got just another question according a different topic:

_Actually I'm using the CCU3 from Homematic and with the SVG-node I'm moving from the "TinyMatic-UI-App" completly to node-red. So I figured out how the workflow for generating a complete SVG-UI along with  you node.
Now I've done some testing and playing around and I build an Excel-Sheet which allows the user to insert a "floorplan" and place different UI-elements for an on/off-device a dimmer, roller blind e.g. By using VBA the SVG-Code is generated with user given names, so that you just have to insert the SVG into the node.....
Further on I'm planning to add the node as an container, so that all needed Events are automatically added too._

**Now the question: I've got so much help from developers like you and now I like to give something back.... Bu I don't know where to post things like this.... Maybe you can give a hint?**

Best regards
Joe

**Comment by bartbutenaers** [comment]
Hey Joe,
Do you mean the Node-RED [forum](https://discourse.nodered.org/)?

**Comment by JoeWiseman** [comment]
OK that might be a good place to post.... I thought that there might be a more specific space .... But I' fine with the common forum!
Thanks again for your great work!

**Comment by bartbutenaers** [comment]
You can always start with *"I'm not sure whether this the correct forum for this topic. "* :-)
